GET http://localhost:8005/admin/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODIxNDk0NDksImlhdCI6MTU4MjE0MjI0OSwidXNlciI6IntcIklEXCI6MSxcIk5hbWVcIjpcIlJvYmVydG9cIixcIlN1cm5hbWVcIjpcIkZlcnJvXCIsXCJVc2VybmFtZVwiOlwidGVzdGVyXCIsXCJQYXNzd29yZFwiOlwiXCJ9In0.5rVe2gyn7M8cDiv0Fd-stsqT4OIqJpx76fgia2l5ALI
###
