GET http://localhost:8005/admin/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODIxMzY0MjEsImlhdCI6MTU4MjEyOTIyMSwidXNlciI6IntcIklEXCI6MixcIk5hbWVcIjpcIlJvYmVydG9cIixcIlN1cm5hbWVcIjpcIkZlcnJvXCIsXCJVc2VybmFtZVwiOlwidGVzdGVyXCIsXCJQYXNzd29yZFwiOlwiXCJ9In0.i0qg1OO6UEaCcUksTXtkkbaDEozchBaugw8fH_1hoHQ
###
