POST http://{{host}}:{{port}}/users
Content-Type: application/json

{
  "name": "{{name}}",
  "surname": "{{surname}}",
  "username": "{{username}}",
  "password": "{{password}}",
  "repeat-password": "{{repeat-password}}"
}

###
